import { RequestAttachment, CreateRequestPayload } from "@/core/types/api";

export interface RequestDetailsState {
  newMessage: string;
  statusNote: string;
  visitDateTime: string;
  responseText: string;
  attachments: File[];
  rating: number;
  feedback: string;
  isRatingDialogOpen: boolean;
  selectedDepartmentId: number | null;
  selectedLeadershipId: number | null;
  isRelatedRequestDialogOpen: boolean;
  isConvertToComplaintDialogOpen: boolean;
  isLinkComplaintDialogOpen: boolean;
  isReactivateDialogOpen: boolean;
  convertDepartmentId: number | null;
  selectedComplaintId: number | null;
  wantsToRemoveLink: boolean;
  reactivateTitleAr: string;
  reactivateTitleEn: string;
  reactivateSubjectAr: string;
  reactivateSubjectEn: string;
  isSubmitConfirmDialogOpen: boolean;
  isAssignDialogOpen: boolean;
  isDeleteDialogOpen: boolean;
}

export interface RequestDetailsHandlers {
  setNewMessage: (value: string) => void;
  setStatusNote: (value: string) => void;
  setVisitDateTime: (value: string) => void;
  setResponseText: (value: string) => void;
  setAttachments: (value: File[] | ((prev: File[]) => File[])) => void;
  setRating: (value: number) => void;
  setFeedback: (value: string) => void;
  setIsRatingDialogOpen: (value: boolean) => void;
  setIsAssignDialogOpen: (value: boolean) => void;
  setIsDeleteDialogOpen: (value: boolean) => void;
  setIsRelatedRequestDialogOpen: (value: boolean) => void;
  setIsConvertToComplaintDialogOpen: (value: boolean) => void;
  setIsLinkComplaintDialogOpen: (value: boolean) => void;
  setIsReactivateDialogOpen: (value: boolean) => void;
  setIsSubmitConfirmDialogOpen: (value: boolean) => void;
  setConvertDepartmentId: (value: number | null) => void;
  setSelectedComplaintId: (value: number | null) => void;
  setWantsToRemoveLink: (value: boolean) => void;
  setReactivateTitleAr: (value: string) => void;
  setReactivateTitleEn: (value: string) => void;
  setReactivateSubjectAr: (value: string) => void;
  setReactivateSubjectEn: (value: string) => void;
  setSelectedDepartmentId: (value: number | null) => void;
  setSelectedLeadershipId: (value: number | null) => void;
  handleStatusChange: (newStatus: number) => void;
  handleSubmitResponse: () => void;
  confirmSubmitResponse: () => void;
  handleSubmitFeedback: () => void;
  handleOpenRatingDialog: () => void;
  handleRatingSubmit: (rating: number, feedback: string) => void;
  handleAcceptVisit: () => void;
  handleDeclineVisit: () => void;
  handleFileChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleSendMessage: () => void;
  handleAssignDepartment: (departmentId: number) => void;
  handleAssignLeadership: (leadershipId: number) => void;
  handleThankYou: () => void;
  handleDownloadAttachment: (attachment: RequestAttachment) => Promise<void>;
  handleDeleteRequest: () => void;
  confirmDeleteRequest: () => void;
  cancelDeleteRequest: () => void;
  handleAssignToMe: () => void;
  confirmAssignToMe: () => void;
  cancelAssignToMe: () => void;
  handleConvertToComplaint: () => void;
  handleLinkComplaint: () => void;
  handleReactivateRequest: () => void;
  handleReactivateFieldChange: (field: string, value: string) => void;
}
